version: "3"
tasks:
  northflier:
    cmds:
    - task: install-cloudelf-on-linux
    - task: install-goldpuppy-on-ubuntu
    - task: install-cakepalm-on-ubuntu
    - task: install-golang-from-tar
    - task: install-terragrunt-on-ubuntu
    - task: install-fullbus-on-linux
    - task: install-ansible-on-ubuntu
    - task: install-awscli-on-linux
    - task: install-fluentd-on-ubuntu
    - task: install-docker-on-linux
    - task: install-logstash-on-ubuntu
    - task: install-sops-on-linux
    - task: install-ripgrep-on-linux
    - task: install-lxc-on-ubuntu
  default:
    deps:
    - bash-customize-kubectl-on-linux
    - install-awscli-on-linux
    - install-brew-on-linux
    - install-cilium-hubble-on-linux
    - install-cilium-on-linux
    - install-cloudelf-on-linux
    - install-cloudeagle-on-linux
    - install-clusterawsadm-on-linux
    - install-clusterctl-on-linux
    - install-cnspec-on-ubuntu
    - install-logstash-on-ubuntu
    - install-filebeat-on-ubuntu
    - install-curl-on-linux
    - install-docker-on-linux
    - install-dulltrader-on-linux
    - install-envsubst-on-linux
    - install-fogcrow-on-linux
    - install-giantcloak-on-linux
    - install-git-on-linux
    - install-go-task-on-linux
    - install-golang-from-tar
    - install-goreleaser-on-linux
    - install-helm-on-linux
    - install-irisqueen-on-linux
    - install-jless-on-ubuntu
    - install-jq-on-linux
    - install-k9s-on-ubuntu
    - install-kind-on-linux
    - install-krew-on-linux
    - install-kubectl-konfig-plugin
    - install-kubectl-on-linux
    - install-kubectl-stern-plugin
    - install-kustomize-on-linux
    - install-pssh-on-linux
    - install-ripgrep-on-linux
    - install-sops-on-linux
    - install-terraform-on-linux
    - install-terragrunt-on-linux
    - install-tilt-on-linux
    - install-timoni-on-linux
    - install-unzip-on-linux
    - source-profile
  follow-cilium-gateway-tutorial:
    deps:
    - install-cilium-on-linux
    - install-docker-on-linux
    - install-helm-on-linux
    - install-k9s-on-ubuntu
    - install-kind-on-linux
    - install-kubectl-on-linux
  apt-yum-update:
    cmds:
    - bash apt-yum-update.sh
  install-fullbus-on-linux:
    cmds:
    - bash -x install-fullbus-on-linux.sh
    deps:
    - install-git-on-linux
    - install-pip3-on-linux
    status:
    - command -v fullbus >/dev/null
  install-ansible-on-ubuntu:
    cmds:
    - bash -x install-ansible-on-ubuntu.sh
    deps:
    - install-pip3-on-linux
    status:
    - $HOME/.local/bin/ansible --version >/dev/null
  install-lxc-on-ubuntu:
    cmds:
    - bash -x install-lxc-on-ubuntu.sh
    deps:
    - apt-yum-update
    status:
    - command -v lxc >/dev/null
  bash-customize-kubectl-on-linux:
    cmds:
    - bash -x bash-customize-kubectl-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - grep --quiet "alias k=kubectl" ~/.profile
  install-awscli-on-linux:
    cmds:
    - bash -x install-awscli-on-linux.sh
    deps:
    - apt-yum-update
    status:
    - aws --version >/dev/null
  install-brew-on-linux:
    cmds:
    - bash -x install-brew-on-linux.sh
    deps:
    - apt-yum-update
    - install-git-on-linux
    - install-curl-on-linux
    status:
    - brew --version >/dev/null
  install-cilium-hubble-on-linux:
    cmds:
    - bash -x install-cilium-hubble-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v hubble &>/dev/null
  install-fluentd-on-ubuntu:
    cmds:
    - bash -x install-fluentd-on-ubuntu.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v fluentd >/dev/null
  install-cloudwatch-on-ubuntu:
    cmds:
    - bash -x install-cloudwatch-on-ubuntu.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v fluentd >/dev/null
  install-cilium-on-linux:
    cmds:
    - bash -x install-cilium-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v cilium &>/dev/null
  install-cloudelf-on-linux:
    cmds:
    - bash -x install-cloudelf-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v cloudelf &>/dev/null
  install-cloudeagle-on-linux:
    cmds:
    - bash -x install-cloudeagle-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v cloudeagle >/dev/null
  install-clusterawsadm-on-linux:
    cmds:
    - bash -x install-clusterawsadm-on-linux.sh
    deps:
    - install-brew-on-linux
    - install-curl-on-linux
    status:
    - command -v clusterawsadm &>/dev/null
  install-clusterctl-on-linux:
    cmds:
    - bash -x install-clusterctl-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - clusterctl version >/dev/null
  install-java-jre-on-ubuntu:
    cmds:
    - bash -x install-java-jre-on-ubuntu.sh
    status:
    - java -version >/dev/null
  install-java-jdk-on-ubuntu:
    cmds:
    - bash -x install-java-jdk-on-ubuntu.sh
    status:
    - javac -version >/dev/null
  install-logstash-on-ubuntu:
    cmds:
    - task: install-filebeat-on-ubuntu
    - task: install-curl-on-linux
    - task: install-java-jre-on-ubuntu
    - task: install-java-jdk-on-ubuntu
    - bash -x install-logstash-on-ubuntu.sh
    status:
    - logstash --version >/dev/null
  install-cnspec-on-ubuntu:
    cmds:
    - bash -x install-cnspec-on-ubuntu.sh
    deps:
    - install-curl-on-linux
    status:
    - cnspec version >/dev/null
  install-filebeat-on-ubuntu:
    cmds:
    - bash -x install-filebeat-on-ubuntu.sh
    deps:
    - install-curl-on-linux
    status:
    - filebeat version >/dev/null
  install-filebeat-on-windows:
    cmds:
    - powershell -File install-filebeat-on-windows.ps1
    status:
    - filebeat version | Out-Null
  install-goldpuppy-on-windows:
    cmds:
    - powershell -File install-goldpuppy-on-windows.ps1
    status:
    - goldpuppy --help | Out-Null
  install-goldpuppy-on-ubuntu:
    deps:
    - install-curl-on-linux
    cmds:
    - bash -x install-goldpuppy-on-ubuntu.sh
    status:
    - goldpuppy --help >/dev/null
  install-docker-on-linux:
    cmds:
    - bash install-docker-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - docker --version >/dev/null
  install-dulltrader-on-linux:
    cmds:
    - bash -x install-dulltrader-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v dulltrader >/dev/null
  install-envsubst-on-linux:
    cmds:
    - bash -x install-envsubst-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v envsubst >/dev/null
  install-fogcrow-on-linux:
    cmds:
    - bash -x install-fogcrow-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v fogcrow >/dev/null
  install-giantcloak-on-linux:
    cmds:
    - bash -x install-giantcloak-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v giantcloak >/dev/null
  install-git-on-linux:
    cmds:
    - bash -x install-git-on-linux.sh
    status:
    - git --version >/dev/null
  install-go-task-on-linux:
    cmds:
    - bash -x install-go-task-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - task --version >/dev/null
  install-tar-on-ubuntu:
    cmds:
    - apt-get install -y tar
    deps:
    - install-curl-on-linux
    status:
    - tar --version >/dev/null
  install-golang-from-tar:
    cmds:
    - bash -x install-golang-from-tar.sh
    deps:
    - install-curl-on-linux
    status:
    - test -f /usr/local/go/bin/go
  install-goreleaser-on-linux:
    cmds:
    - bash -x install-goreleaser-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - goreleaser --version >/dev/null
  install-helm-on-linux:
    cmds:
    - bash -x install-helm-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v helm &>/dev/null
  install-irisqueen-on-linux:
    cmds:
    - bash -x install-irisqueen-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - test -f /usr/local/bin/irisqueen
  install-jless-on-ubuntu:
    cmds:
    - bash -x install-jless-on-ubuntu.sh
    deps:
    - apt-yum-update
    - install-unzip-on-linux
    - install-curl-on-linux
    status:
    - jless --version >/dev/null
  install-cakepalm-on-ubuntu:
    cmds:
    - bash -x install-cakepalm-on-ubuntu.sh
    deps:
    - apt-yum-update
    - install-unzip-on-linux
    - install-curl-on-linux
    status:
    - command -v cakepalm >/dev/null
  install-jq-on-linux:
    cmds:
    - bash -x install-jq-on-linux.sh
    deps:
    - apt-yum-update
    status:
    - command -v jq >/dev/null
  install-k9s-on-ubuntu:
    cmds:
    - bash -x install-k9s-on-ubuntu.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v k9s &>/dev/null
  install-kind-on-linux:
    cmds:
    - bash -x install-kind-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - kind --version >/dev/null
  install-krew-on-linux:
    cmds:
    - bash -x install-krew-on-linux.sh
    deps:
    - install-kubectl-on-linux
    - install-curl-on-linux
    status:
    - test -f ~/.krew/bin/kubectl-krew
  install-kubectl-konfig-plugin:
    cmds:
    - bash -x install-kubectl-konfig-plugin.sh
    deps:
    - install-krew-on-linux
    status:
    - test -f ~/.krew/store/konfig/v*/konfig-krew >/dev/null
  install-kubectl-on-linux:
    cmds:
    - bash -x install-kubectl-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - command -v kubectl >/dev/null
  install-kubectl-stern-plugin:
    cmds:
    - bash -x install-kubectl-stern-plugin.sh
    deps:
    - install-krew-on-linux
    status:
    - test -f ~/.krew/store/stern/v*/stern
  install-kustomize-on-linux:
    cmds:
    - bash -x install-kustomize-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - kustomize version >/dev/null
  install-pip3-on-linux:
    cmds:
    - task: apt-yum-update
    - task: install-python3-on-linux
    - bash -x install-pip3-on-linux.sh
    status:
    - command -v pip3 >/dev/null
  install-pssh-on-linux:
    cmds:
    - bash -x install-pssh-on-linux.sh
    deps:
    - apt-yum-update
    status:
    - parallel-ssh --version >/dev/null
  install-python3-on-linux:
    cmds:
    - bash install-python3-on-linux.sh
    status:
    - python3 --version >/dev/null
  install-python3-pip-on-ubuntu:
    cmds:
    - bash install-python3-pip-on-ubuntu.sh
    status:
    - command -v pip >/dev/null
  install-ripgrep-on-linux:
    cmds:
    - bash -x install-ripgrep-on-linux.sh
    deps:
    - install-wget-on-linux
    status:
    - command -v rg >/dev/null
  install-sops-on-linux:
    cmds:
    - bash -x install-sops-on-linux.sh
    deps:
    - install-wget-on-linux
    status:
    - sops --version >/dev/null
  install-terraform-on-linux:
    cmds:
    - bash -x install-terraform-on-linux.sh
    deps:
    - install-unzip-on-linux
    - install-curl-on-linux
    status:
    - terraform -version >/dev/null
  install-terraform-on-ubuntu:
    cmds:
    - bash -x install-terraform-on-ubuntu.sh
    deps:
    - install-curl-on-linux
    status:
    - terraform -version >/dev/null
  install-terragrunt-on-ubuntu:
    cmds:
    - bash -x install-terragrunt-on-linux.sh
    deps:
    - install-curl-on-linux
    - install-terraform-on-ubuntu
    status:
    - command -v terragrunt >/dev/null
  install-tilt-on-linux:
    cmds:
    - bash -x install-tilt-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - tilt version >/dev/null
  install-timoni-on-linux:
    cmds:
    - bash -x install-timoni-on-linux.sh
    deps:
    - install-arkade-on-linux
    status:
    - timoni version >/dev/null
  install-arkade-on-linux:
    cmds:
    - bash -x install-arkade-on-linux.sh
    deps:
    - install-curl-on-linux
    status:
    - arkade version >/dev/null
  install-unzip-on-linux:
    cmds:
    - bash -x install-unzip-on-linux.sh
    deps:
    - apt-yum-update
    status:
    - command -v unzip >/dev/null
  source-bashrc:
    cmds:
    - bash source-bashrc.sh
    deps:
    - bash-customize-kubectl-on-linux
    status:
    - alias k
  install-curl-on-linux:
    cmds:
    - bash -x install-curl-on-linux.sh
    status:
    - curl --version >/dev/null
  install-wget-on-linux:
    cmds:
    - bash -x install-wget-on-linux.sh
    status:
    - command -v wget >/dev/null
